trigger:
- master

jobs:
- job: windows
  pool:
    vmImage: windows-latest
  steps:
  - template: ./ci/templates/powershell.yaml

- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: ./ci/templates/powershell.yaml
