trigger:
- master

jobs:
- job: windowsPowerShellV6
  pool:
    name: 'Self-hosted pool'
  steps:
  - template: ./templates/powershell.yaml

- job: windowsPowerShellV7
  pool:
    vmImage: windows-latest
  steps:
  - template: ./templates/powershell.yaml

- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: ./templates/powershell.yaml
