trigger:
- master

jobs:
- job: windows
  pool:
    name: 'Self-hosted pool'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        node -v
        cd package-test
        Get-Host | Select-Object Version
        npm pack .
        npm ping
      errorActionPreference: 'continue'
      pwsh: true
    displayName: 'Windows test'

- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        cd package-test
        npm pack .
      errorActionPreference: 'continue'
      pwsh: true
      displayName: 'Ubuntu test'
