trigger:
- master

jobs:
- job: windows
  pool:
    name: 'Self-hosted pool'
  steps:
    - pwsh: |
      Set-Location "package-test"
      $oldEAPreference = $ErrorActionPreference
      $ErrorActionPreference = "SilentlyContinue"
      try {
        $PackageName = &{ npm pack . }
        $ec = $LASTEXITCODE
        Write-Host "npm pack terminated with exit code #$ec"
      } catch {
        $ec = -1
      } finally {
        $ErrorActionPreference = $oldEAPreference
      }
      if ($ec -ne 0) {
        Write-Host "##vso[task.complete result=Failed;]npm pack failed with exit code #$ec"
        exit 1
      }
      Write-Host "Produced package '$PackageName'"
      Write-Host "##vso[task.setvariable variable=PackedLibraryFilename]$PackageName"
    displayName: 'Pack NPM (library)'
    failOnStderr: false
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       cd package-test
  #       npm pack .
  #     errorActionPreference: 'continue'
  #     pwsh: true
  #   displayName: 'Windows test'

- job: linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        cd package-test
        npm pack .
      errorActionPreference: 'continue'
      pwsh: true
      displayName: 'Ubuntu test'
